services:
    app:
        container_name: kassa
        image: sarastro72/kassa:test
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "5555:80"
